const symptomData = [
    {
        symptoms: ['Fever', 'Cough', 'Fatigue', 'Headache'],
        disease: 'Common Cold',
        treatment: 'Rest, hydration, and over-the-counter cold medications',
        medicines: ['Paracetamol', 'Ibuprofen'],
        guidance: 'Home treatable',
    },
    {
        symptoms: ['High Fever', 'Severe Headache', 'Stiff Neck'],
        disease: 'Meningitis',
        treatment: 'Immediate hospital treatment with antibiotics or antiviral medications',
        medicines: ['Ceftriaxone', 'Vancomycin'],
        guidance: 'Critical - Seek hospital care',
    },
    {
        symptoms: ['Cough', 'Shortness of Breath', 'Fatigue'],
        disease: 'Pneumonia',
        treatment: 'Antibiotics, rest, and fluids',
        medicines: ['Amoxicillin', 'Azithromycin'],
        guidance: 'Medical consultation required',
    },
    {
        symptoms: ['Sore Throat', 'Fever', 'Swollen Lymph Nodes'],
        disease: 'Strep Throat',
        treatment: 'Antibiotics like Penicillin',
        medicines: ['Penicillin', 'Amoxicillin'],
        guidance: 'Requires medical treatment',
    },
    {
        symptoms: ['Nausea', 'Vomiting', 'Stomach Pain'],
        disease: 'Gastroenteritis',
        treatment: 'Hydration and over-the-counter medications for nausea',
        medicines: ['Ondansetron', 'Loperamide'],
        guidance: 'Home treatable, consult if symptoms worsen',
    },
    {
        symptoms: ['Fatigue', 'Weight Gain', 'Cold Sensitivity'],
        disease: 'Hypothyroidism',
        treatment: 'Thyroid hormone replacement therapy',
        medicines: ['Levothyroxine'],
        guidance: 'Consult a doctor for a prescription',
    },
    {
        symptoms: ['Chronic Cough', 'Wheezing', 'Shortness of Breath'],
        disease: 'Asthma',
        treatment: 'Inhalers, corticosteroids, and avoiding triggers',
        medicines: ['Albuterol', 'Fluticasone'],
        guidance: 'Manageable with medication',
    },
    {
        symptoms: ['Persistent High Fever', 'Night Sweats', 'Fatigue'],
        disease: 'Tuberculosis',
        treatment: 'Antibiotics for at least 6 months',
        medicines: ['Isoniazid', 'Rifampin'],
        guidance: 'Requires long-term medical treatment',
    },
    {
        symptoms: ['Painful Urination', 'Frequent Urination', 'Lower Abdominal Pain'],
        disease: 'Urinary Tract Infection (UTI)',
        treatment: 'Antibiotics and plenty of fluids',
        medicines: ['Ciprofloxacin', 'Nitrofurantoin'],
        guidance: 'Consult a doctor for antibiotics',
    },
    {
        symptoms: ['Joint Pain', 'Fatigue', 'Skin Rashes'],
        disease: 'Rheumatoid Arthritis',
        treatment: 'Disease-modifying antirheumatic drugs (DMARDs)',
        medicines: ['Methotrexate', 'Hydroxychloroquine'],
        guidance: 'Requires medical treatment and ongoing management',
    },
    {
        symptoms: ['Chest Pain', 'Shortness of Breath', 'Fatigue'],
        disease: 'Heart Attack',
        treatment: 'Immediate emergency treatment, including surgery if needed',
        medicines: ['Aspirin', 'Clopidogrel'],
        guidance: 'Immediate emergency care required',
    },
    {
        symptoms: ['Abdominal Pain', 'Jaundice', 'Dark Urine'],
        disease: 'Hepatitis',
        treatment: 'Antiviral medications, avoid alcohol',
        medicines: ['Entecavir', 'Tenofovir'],
        guidance: 'Requires medical consultation and treatment',
    },
    {
        symptoms: ['Severe Back Pain', 'Numbness', 'Weakness in Legs'],
        disease: 'Spinal Cord Injury',
        treatment: 'Emergency care, surgical intervention if needed',
        medicines: ['Pain relievers', 'Steroids'],
        guidance: 'Seek emergency medical attention',
    },
    {
        symptoms: ['Severe Thirst', 'Frequent Urination', 'Fatigue'],
        disease: 'Diabetes Mellitus',
        treatment: 'Blood sugar management through medication and diet',
        medicines: ['Metformin', 'Insulin'],
        guidance: 'Manageable with long-term treatment',
    },
    {
        symptoms: ['Sudden Loss of Vision', 'Pain around the Eye'],
        disease: 'Glaucoma',
        treatment: 'Eye drops to lower intraocular pressure, surgery if necessary',
        medicines: ['Timolol', 'Latanoprost'],
        guidance: 'Requires medical consultation and treatment',
    },

    // Additional 15 entries
    {
        symptoms: ['Severe Headache', 'Neck Stiffness', 'Sensitivity to Light'],
        disease: 'Migraine',
        treatment: 'Pain relievers, rest in a dark room, and hydration',
        medicines: ['Sumatriptan', 'Ibuprofen'],
        guidance: 'Home treatable or consult if symptoms persist',
    },
    {
        symptoms: ['Red, Itchy Eyes', 'Excessive Tearing', 'Blurry Vision'],
        disease: 'Conjunctivitis (Pink Eye)',
        treatment: 'Antibiotic eye drops or antihistamine',
        medicines: ['Chloramphenicol', 'Olopatadine'],
        guidance: 'Home treatable, consult if severe',
    },
    {
        symptoms: ['Sudden Weight Loss', 'Excessive Thirst', 'Frequent Urination'],
        disease: 'Diabetes Insipidus',
        treatment: 'Desmopressin, hydration therapy',
        medicines: ['Desmopressin'],
        guidance: 'Requires ongoing management',
    },
    {
        symptoms: ['Painful Swallowing', 'Sore Throat', 'Hoarseness'],
        disease: 'Laryngitis',
        treatment: 'Resting the voice, hydration, and throat lozenges',
        medicines: ['Hydrocodone', 'Dexamethasone'],
        guidance: 'Home treatable, consult if symptoms persist',
    },
    {
        symptoms: ['Dry Skin', 'Flaky Scalp', 'Hair Loss'],
        disease: 'Psoriasis',
        treatment: 'Topical creams, UV therapy, and oral medications',
        medicines: ['Hydrocortisone', 'Methotrexate'],
        guidance: 'Manageable with treatment',
    },
    {
        symptoms: ['Sore Muscles', 'Fever', 'Headache'],
        disease: 'Influenza (Flu)',
        treatment: 'Rest, hydration, and antiviral medications',
        medicines: ['Oseltamivir', 'Paracetamol'],
        guidance: 'Home treatable or consult if symptoms worsen',
    },
    {
        symptoms: ['Dark, Urine', 'Fatigue', 'Loss of Appetite'],
        disease: 'Liver Disease',
        treatment: 'Liver function support and medications',
        medicines: ['Lactulose', 'Sodium Bicarbonate'],
        guidance: 'Requires medical consultation',
    },
    {
        symptoms: ['Nausea', 'Shortness of Breath', 'Coughing up Blood'],
        disease: 'Pulmonary Embolism',
        treatment: 'Emergency medical care, anticoagulant therapy',
        medicines: ['Heparin', 'Warfarin'],
        guidance: 'Immediate medical intervention required',
    },
    {
        symptoms: ['Dry Cough', 'Fatigue', 'Weight Loss'],
        disease: 'Chronic Obstructive Pulmonary Disease (COPD)',
        treatment: 'Bronchodilators, steroids, and pulmonary rehabilitation',
        medicines: ['Salbutamol', 'Prednisone'],
        guidance: 'Manageable with medication and lifestyle changes',
    },
    {
        symptoms: ['Fatigue', 'Headache', 'Dizziness'],
        disease: 'Anemia',
        treatment: 'Iron supplements, balanced diet',
        medicines: ['Ferrous Sulfate', 'Folic Acid'],
        guidance: 'Consult for proper diagnosis and treatment',
    },
    {
        symptoms: ['Red Skin', 'Pain', 'Itchiness'],
        disease: 'Eczema',
        treatment: 'Topical corticosteroids, moisturizers',
        medicines: ['Hydrocortisone', 'Tacrolimus'],
        guidance: 'Manageable with topical treatment',
    },
    {
        symptoms: ['Painful Rash', 'Blisters', 'Fever'],
        disease: 'Shingles',
        treatment: 'Antiviral medications and pain relief',
        medicines: ['Acyclovir', 'Gabapentin'],
        guidance: 'Consult a doctor for antiviral treatment',
    },
    {
        symptoms: ['Painful Joints', 'Fever', 'Rash'],
        disease: 'Systemic Lupus Erythematosus (SLE)',
        treatment: 'Immunosuppressive drugs and symptom management',
        medicines: ['Hydroxychloroquine', 'Prednisone'],
        guidance: 'Requires medical management',
    },
    {
        symptoms: ['Difficulty Breathing', 'Swelling', 'Itchiness'],
        disease: 'Anaphylaxis',
        treatment: 'Emergency care with epinephrine',
        medicines: ['Epinephrine', 'Antihistamines'],
        guidance: 'Immediate emergency treatment required',
    },
];

export default symptomData;
